### ISSUE TITLE
Sitemap:refresh throws error

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#2471]
Tried to run this from terminal. Assuming that the automatic update is not working either. trace below:

```
➜  unpacking git:(master) heroku run rake sitemap:refresh -a ebwiki
Running rake sitemap:refresh on ⬢ ebwiki... up, run.5040 (Standard-1X)
** [NewRelic][2018-10-01 17:58:42 +0000 run.* (4)] INFO : Starting the New Relic agent version 5.2.0.345 in "production" environment.
** [NewRelic][2018-10-01 17:58:42 +0000 run.* (4)] INFO : To prevent agent startup add a NEW_RELIC_AGENT_ENABLED=false environment variable or modify the "production" section of your newrelic.yml.
** [NewRelic][2018-10-01 17:58:42 +0000 run.* (4)] INFO : Reading configuration from config/newrelic.yml (/app)
** [NewRelic][2018-10-01 17:58:42 +0000 run.* (4)] INFO : Environment: production
** [NewRelic][2018-10-01 17:58:42 +0000 run.* (4)] INFO : No known dispatcher detected.
** [NewRelic][2018-10-01 17:58:42 +0000 run.* (4)] INFO : Application: EBWiki
** [NewRelic][2018-10-01 17:58:42 +0000 run.* (4)] INFO : Installing Redis Instrumentation
** [NewRelic][2018-10-01 17:58:42 +0000 run.* (4)] INFO : Installing Sinatra instrumentation
** [NewRelic][2018-10-01 17:58:42 +0000 run.* (4)] INFO : Installing Net instrumentation
** [NewRelic][2018-10-01 17:58:42 +0000 run.* (4)] INFO : Installing deferred Rack::Builder instrumentation
** [NewRelic][2018-10-01 17:58:42 +0000 run.* (4)] INFO : Installing Rack::Builder middleware instrumentation
** [NewRelic][2018-10-01 17:58:42 +0000 run.* (4)] INFO : Installing Rails 3+ middleware instrumentation
** [NewRelic][2018-10-01 17:58:42 +0000 run.* (4)] INFO : Installing ActiveRecord 4 instrumentation
** [NewRelic][2018-10-01 17:58:42 +0000 run.* (4)] INFO : Installing middleware-based Excon instrumentation
** [NewRelic][2018-10-01 17:58:42 +0000 run.* (4)] INFO : Installing ActiveJob instrumentation
** [NewRelic][2018-10-01 17:58:42 +0000 run.* (4)] INFO : Installing Rails 4 view instrumentation
** [NewRelic][2018-10-01 17:58:42 +0000 run.* (4)] INFO : Installing Rails 4 Controller instrumentation
** [NewRelic][2018-10-01 17:58:42 +0000 run.* (4)] INFO : Finished instrumentation
In '/app/tmp/':
** [NewRelic][2018-10-01 17:58:45 +0000 run.* (4)] INFO : Reporting to: https://rpm.newrelic.com/accounts/973384/applications/28605167
[Rollbar] Scheduling item
[Rollbar] Sending item
[Rollbar] Success
[Rollbar] Details: https://rollbar.com/instance/uuid?uuid=c25f68f7-58f2-4ba2-8da6-02ff91aaac03 (only available if report was successful)
rake aborted!
NoMethodError: undefined method `yaml_as' for SitemapGenerator::BigDecimal:Class
Did you mean?  yaml_tag
/app/vendor/bundle/ruby/2.5.0/gems/sitemap_generator-6.0.0/lib/sitemap_generator/core_ext/big_decimal.rb:15:in `<class:BigDecimal>'
/app/vendor/bundle/ruby/2.5.0/gems/sitemap_generator-6.0.0/lib/sitemap_generator/core_ext/big_decimal.rb:11:in `<top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/app/vendor/bundle/ruby/2.5.0/gems/sitemap_generator-6.0.0/lib/sitemap_generator/helpers/number_helper.rb:129:in `number_with_precision'
/app/vendor/bundle/ruby/2.5.0/gems/sitemap_generator-6.0.0/lib/sitemap_generator/helpers/number_helper.rb:231:in `number_to_human_size'
/app/vendor/bundle/ruby/2.5.0/gems/sitemap_generator-6.0.0/lib/sitemap_generator/sitemap_location.rb:172:in `summary'
/app/vendor/bundle/ruby/2.5.0/gems/sitemap_generator-6.0.0/lib/sitemap_generator/sitemap_location.rb:167:in `write'
/app/vendor/bundle/ruby/2.5.0/gems/sitemap_generator-6.0.0/lib/sitemap_generator/builder/sitemap_file.rb:139:in `write'
/app/vendor/bundle/ruby/2.5.0/gems/sitemap_generator-6.0.0/lib/sitemap_generator/builder/sitemap_index_file.rb:138:in `write_first_sitemap'
/app/vendor/bundle/ruby/2.5.0/gems/sitemap_generator-6.0.0/lib/sitemap_generator/builder/sitemap_index_file.rb:104:in `finalize!'
/app/vendor/bundle/ruby/2.5.0/gems/sitemap_generator-6.0.0/lib/sitemap_generator/link_set.rb:468:in `finalize_sitemap_index!'
/app/vendor/bundle/ruby/2.5.0/gems/sitemap_generator-6.0.0/lib/sitemap_generator/link_set.rb:339:in `finalize!'
/app/vendor/bundle/ruby/2.5.0/gems/sitemap_generator-6.0.0/lib/sitemap_generator/link_set.rb:41:in `create'
/app/vendor/bundle/ruby/2.5.0/gems/sitemap_generator-6.0.0/lib/sitemap_generator.rb:41:in `method_missing'
/app/config/sitemap.rb:26:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/sitemap_generator-6.0.0/lib/sitemap_generator/interpreter.rb:78:in `instance_eval'
/app/vendor/bundle/ruby/2.5.0/gems/sitemap_generator-6.0.0/lib/sitemap_generator/interpreter.rb:78:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/sitemap_generator-6.0.0/lib/sitemap_generator/tasks.rb:51:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:27:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli.rb:360:in `exec'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli.rb:20:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/cli.rb:10:in `start'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/exe/bundle:30:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/exe/bundle:22:in `<top (required)>'
/app/bin/bundle:5:in `load'
/app/bin/bundle:5:in `<main>'
Tasks: TOP => sitemap:refresh => sitemap:create
(See full trace by running task with --trace)
➜  unpacking git:(master) 
```

**Comment by rlgreen91** [comment]
It is.  Closing this and making new issue with fix.
