### ISSUE TITLE
Admin page not working

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#2601]
```2018-10-22T01:49:59.842989+00:00 app[web.1]: Started GET "/admin" for 108.162.219.71 at 2018-10-22 01:49:59 +0000
2018-10-22T01:49:59.846863+00:00 app[web.1]: Processing by RailsAdmin::MainController#dashboard as HTML
2018-10-22T01:50:00.112884+00:00 app[web.1]: Completed 500 Internal Server Error in 266ms (ActiveRecord: 173.7ms)
2018-10-22T01:50:00.152267+00:00 app[web.1]: [Rollbar] Scheduling item
2018-10-22T01:50:00.152365+00:00 app[web.1]: [Rollbar] Sending item
2018-10-22T01:50:00.245914+00:00 app[web.1]: [Rollbar] Success
2018-10-22T01:50:00.245998+00:00 app[web.1]: [Rollbar] Details: https://rollbar.com/instance/uuid?uuid=02cd12c8-66e4-47b8-96c5-d734ff176a71 (only available if report was successful)
2018-10-22T01:50:00.249940+00:00 app[web.1]: 
2018-10-22T01:50:00.249943+00:00 app[web.1]: ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "calender_events" does not exist
2018-10-22T01:50:00.249946+00:00 app[web.1]: LINE 5:                WHERE a.attrelid = '"calender_events"'::regcl...
2018-10-22T01:50:00.249948+00:00 app[web.1]: ^
2018-10-22T01:50:00.249950+00:00 app[web.1]: :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
2018-10-22T01:50:00.249952+00:00 app[web.1]: pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
2018-10-22T01:50:00.249954+00:00 app[web.1]: FROM pg_attribute a LEFT JOIN pg_attrdef d
2018-10-22T01:50:00.249955+00:00 app[web.1]: ON a.attrelid = d.adrelid AND a.attnum = d.adnum
2018-10-22T01:50:00.249957+00:00 app[web.1]: WHERE a.attrelid = '"calender_events"'::regclass
2018-10-22T01:50:00.249958+00:00 app[web.1]: AND a.attnum > 0 AND NOT a.attisdropped
2018-10-22T01:50:00.249960+00:00 app[web.1]: ORDER BY a.attnum
2018-10-22T01:50:00.249962+00:00 app[web.1]: ):
2018-10-22T01:50:00.249964+00:00 app[web.1]: vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
2018-10-22T01:50:00.249966+00:00 app[web.1]: vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
```

**Comment by rlgreen91** [comment]
This has been addressed with the PR #2578
