### ISSUE TITLE
Can't add agencies to case via edit form

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#3613]
App throws an error when agency is added. Here is the trace:

```
2020-07-05T09:28:11.511429+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de]
2020-07-05T09:28:11.511466+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] ActionController::RoutingError (No route matches [POST] "/cases/valente-acosta-bustillos"):
2020-07-05T09:28:11.511537+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de]
2020-07-05T09:28:11.511646+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
2020-07-05T09:28:11.511647+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/rollbar-2.19.4/lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
2020-07-05T09:28:11.511648+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
2020-07-05T09:28:11.511649+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
2020-07-05T09:28:11.511649+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
2020-07-05T09:28:11.511650+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
2020-07-05T09:28:11.511650+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/rack/logger.rb:24:in `block in call'
2020-07-05T09:28:11.511651+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/tagged_logging.rb:69:in `block in tagged'
2020-07-05T09:28:11.511651+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/tagged_logging.rb:26:in `tagged'
2020-07-05T09:28:11.511651+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/tagged_logging.rb:69:in `tagged'
2020-07-05T09:28:11.511653+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/rack/logger.rb:24:in `call'
2020-07-05T09:28:11.511653+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
2020-07-05T09:28:11.511654+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
2020-07-05T09:28:11.511654+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
2020-07-05T09:28:11.511655+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/request_id.rb:24:in `call'
2020-07-05T09:28:11.511655+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
2020-07-05T09:28:11.511656+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/method_override.rb:24:in `call'
2020-07-05T09:28:11.511656+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
2020-07-05T09:28:11.511657+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
2020-07-05T09:28:11.511657+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
2020-07-05T09:28:11.511658+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.7.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
2020-07-05T09:28:11.511658+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
2020-07-05T09:28:11.511659+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
2020-07-05T09:28:11.511659+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
2020-07-05T09:28:11.511660+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/static.rb:136:in `call'
2020-07-05T09:28:11.511660+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
2020-07-05T09:28:11.511660+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
2020-07-05T09:28:11.511666+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
2020-07-05T09:28:11.511667+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/rack-cors-1.0.6/lib/rack/cors.rb:98:in `call'
2020-07-05T09:28:11.511667+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
2020-07-05T09:28:11.511667+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/railties-5.0.7.2/lib/rails/engine.rb:522:in `call'
2020-07-05T09:28:11.511668+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-5.2.0.345/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
2020-07-05T09:28:11.511668+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/configuration.rb:228:in `call'
2020-07-05T09:28:11.511669+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/server.rb:713:in `handle_request'
2020-07-05T09:28:11.511669+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/server.rb:472:in `process_client'
2020-07-05T09:28:11.511669+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/server.rb:328:in `block in run'
2020-07-05T09:28:11.511670+00:00 app[web.1]: [6cff8fa7-f858-4dbb-a2bd-217df720a8de] vendor/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
2020-07-05T09:28:11.513633+00:00 heroku[router]: at=info method=POST path="/cases/valente-acosta-bustillos" host=ebwiki.org request_id=6cff8fa7-f858-4dbb-a2bd-217df720a8de fwd="98.109.167.163,108.162.219.45" dyno=web.1 connect=0ms service=11ms status=404 bytes=1758 protocol=https
```

**Comment by campgurus** [comment]
The agency addition worked last time so not sure what the issue is.

**Comment by rlgreen91** [comment]
Can you remember anything else about when this failed @campgurus?  I just tried to reproduce this again and was able to add an agency via the edit form.

**Comment by campgurus** [comment]
Agency form works, and actually, adding a newly created agency to the case
works as well.

To replicate the problem:

   1. go to a case that has no agency or create a new case.
   2. refresh the page to let the agency field format itself for token
   inputs
   3. type in the field to select agency
   4. click to save the case.

You should get an error and the agency will not be added to the case.

**Comment by rlgreen91** [comment]
No, that's what I did - and I was able to successfully add the agency to the case.  That's why I'm asking if there was anything specific to the case that you remember.

**Comment by rlgreen91** [comment]
If you work on this for Hacktoberfest, the first thing you'll need to do is reproduce this on the live site.  If you can't, leave a note here.
