### ISSUE TITLE
Redirect after editing article not working properly

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#870]
I was editng this case to add an agency: https://ebwiki.org/articles/alzona-fiero-smith.

However, when I submitted the update, i saw the 404 message, "this page cannot be found. refreshing the page had no effect. However the url seemed to be identical to the above: the case I was editing.  

Returning back to the original page and refreshing showed the expected edits in place, so this only affects the editors, but it seems odd. 

Stack trace:

```2017-02-19T11:43:52.695789+00:00 heroku[router]: at=info method=GET path="/" host=ebwiki.org request_id=a787a4f0-5ecc-44de-a3e3-f37d067af07e fwd="35.166.6.132,108.162.245.132" dyno=web.1 connect=37ms service=825ms status=200 bytes=8922
2017-02-19T11:43:55.152575+00:00 heroku[router]: at=info method=POST path="/ahoy/events" host=ebwiki.org request_id=44661aae-5d1a-46aa-84db-a3c871a50788 fwd="72.76.197.157,162.158.62.162" dyno=web.1 connect=58ms service=70ms status=200 bytes=1092
2017-02-19T11:43:55.165336+00:00 heroku[router]: at=info method=POST path="/ahoy/events" host=ebwiki.org request_id=28f46803-62e4-4856-adf1-b5637c5af64c fwd="72.76.197.157,162.158.62.162" dyno=web.1 connect=0ms service=34ms status=200 bytes=1092
2017-02-19T11:44:03.130515+00:00 app[web.1]: Started PATCH "/articles/alzona-fiero-smith" for 162.158.62.162 at 2017-02-19 11:44:03 +0000
2017-02-19T11:44:03.217533+00:00 app[web.1]: Processing by ArticlesController#update as HTML
2017-02-19T11:44:03.217623+00:00 app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"sK1/tFIa76ECUsgr8TcJ9uSk77LCJhWpsjYP79LwrxuhhHDrr9/TSFP2DzwocE2JWRuOCm1q+ys3B2Rt5Q4Vcw==", "article"=>{"title"=>"Alzona Fiero Smith", "date"=>"01/11/2015", "remove_avatar"=>"0", "video_url"=>"", "category_id"=>"1", "subjects_attributes"=>{"0"=>{"name"=>"Alzona Fiero Smith", "age"=>"27", "gender_id"=>"1", "ethnicity_id"=>"1", "unarmed"=>"1", "mentally_ill"=>"0", "homeless"=>"0", "veteran"=>"0", "_destroy"=>"false", "id"=>"896"}}, "address"=>"", "city"=>"Washington", "state_id"=>"9", "zipcode"=>"", "overview"=>"<p>At approximately 4:03 am, members of the Seventh District responded for the report of an assault in progress at a residential building in the block. They arrived on scene to find an adult male subject <a href=\"http://dcist.com/2015/11/mpd_investigate_death_of_man_in_spe.php\">handcuffed and in the custody of special police officers working at the location</a>, unconscious and not breathing. Members summoned medical aid and began lifesaving efforts. The subject was transported to an area hospital where he later died.</p>\r\n", "litigation"=>"", "community_action"=>"", "agency_ids"=>["", "534"], "links_attributes"=>{"0"=>{"url"=>"http://dcist.com/2015/11/mpd_investigate_death_of_man_in_spe.php", "_destroy"=>"false", "id"=>"4425"}, "1"=>{"url"=>"https://www.facebook.com/Justice4Zo/?fref=nf", "_destroy"=>"false", "id"=>"4426"}, "2"=>{"url"=>"https://www.washingtonpost.com/local/dc-politics/dc-to-release-body-cam-video-of-man-whom-police-tried-to-save/2015/12/15/e277740a-a365-11e5-9c4e-be37f66848bb_story.html", "_destroy"=>"false", "id"=>"4427"}}, "summary"=>"Adding agency."}, "commit"=>"Update Article", "id"=>"alzona-fiero-smith"}
2017-02-19T11:44:03.275055+00:00 app[web.1]:   User Load (55.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
2017-02-19T11:44:03.320905+00:00 app[web.1]:   Article Load (17.3ms)  SELECT  "articles".* FROM "articles" WHERE "articles"."slug" = $1  ORDER BY "articles"."id" ASC LIMIT 1  [["slug", "alzona-fiero-smith"]]
2017-02-19T11:44:03.323295+00:00 app[web.1]:   CACHE (0.0ms)  SELECT  "articles".* FROM "articles" WHERE "articles"."slug" = $1  ORDER BY "articles"."id" ASC LIMIT 1  [["slug", "alzona-fiero-smith"]]
2017-02-19T11:44:03.345720+00:00 app[web.1]:    (10.7ms)  BEGIN
2017-02-19T11:44:03.350498+00:00 app[web.1]:   Agency Load (2.3ms)  SELECT  "agencies".* FROM "agencies" WHERE "agencies"."id" = $1 LIMIT 1  [["id", 534]]
2017-02-19T11:44:03.361922+00:00 app[web.1]:   Agency Load (9.7ms)  SELECT "agencies".* FROM "agencies" INNER JOIN "article_agencies" ON "agencies"."id" = "article_agencies"."agency_id" WHERE "article_agencies"."article_id" = $1  [["article_id", 932]]
2017-02-19T11:44:03.371017+00:00 app[web.1]:   SQL (5.5ms)  INSERT INTO "article_agencies" ("article_id", "agency_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["article_id", 932], ["agency_id", 534], ["created_at", "2017-02-19 11:44:03.364151"], ["updated_at", "2017-02-19 11:44:03.364151"]]
2017-02-19T11:44:03.384787+00:00 app[web.1]:   Link Load (3.1ms)  SELECT "links".* FROM "links" WHERE "links"."article_id" = $1 AND "links"."id" IN (4425, 4426, 4427)  [["article_id", 932]]
2017-02-19T11:44:03.393806+00:00 app[web.1]:   Subject Load (0.9ms)  SELECT "subjects".* FROM "subjects" WHERE "subjects"."article_id" = $1 AND "subjects"."id" = 896  [["article_id", 932]]
2017-02-19T11:44:03.465729+00:00 app[web.1]:   Article Exists (7.9ms)  SELECT  1 AS one FROM "articles" WHERE ("articles"."id" != 932) AND "articles"."slug" = $1 LIMIT 1  [["slug", "alzona-fiero-smith"]]
2017-02-19T11:44:03.479888+00:00 app[web.1]:   Subject Load (12.1ms)  SELECT "subjects".* FROM "subjects" WHERE "subjects"."article_id" = $1  [["article_id", 932]]
2017-02-19T11:44:03.511487+00:00 app[web.1]:   State Load (26.1ms)  SELECT  "states".* FROM "states" WHERE "states"."id" = $1 LIMIT 1  [["id", 9]]
2017-02-19T11:44:03.802238+00:00 app[web.1]:   SQL (67.1ms)  UPDATE "articles" SET "summary" = $1, "updated_at" = $2 WHERE "articles"."id" = $3  [["summary", "Adding agency."], ["updated_at", "2017-02-19 11:44:03.733553"], ["id", 932]]
2017-02-19T11:44:03.865582+00:00 app[web.1]:    (61.6ms)  COMMIT
2017-02-19T11:44:03.892094+00:00 app[web.1]:   Article Store (26.0ms)  {"id":932}
2017-02-19T11:44:03.962770+00:00 app[web.1]:   PaperTrail::Version Load (68.6ms)  SELECT  "versions".* FROM "versions" WHERE "versions"."item_id" = $1 AND "versions"."item_type" = $2  ORDER BY "versions"."created_at" DESC, "versions"."id" DESC LIMIT 1  [["item_id", 932], ["item_type", "Article"]]
2017-02-19T11:44:04.026396+00:00 app[web.1]:   Follow Load (61.2ms)  SELECT "follows".* FROM "follows" WHERE "follows"."followable_id" = $1 AND "follows"."followable_type" = $2 AND "follows"."blocked" = $3  [["followable_id", 932], ["followable_type", "Article"], ["blocked", "f"]]
2017-02-19T11:44:04.106743+00:00 app[web.1]:   User Load (72.6ms)  SELECT "users".* FROM "users" WHERE "users"."id" IN (43)
2017-02-19T11:44:04.109863+00:00 app[web.1]: UserNotifier#send_followers_email: Sending notification to steve_berry75@hotmail.com about case Alzona Fiero Smith
2017-02-19T11:44:04.111387+00:00 app[web.1]:   CACHE (0.0ms)  SELECT  "versions".* FROM "versions" WHERE "versions"."item_id" = $1 AND "versions"."item_type" = $2  ORDER BY "versions"."created_at" DESC, "versions"."id" DESC LIMIT 1  [["item_id", 932], ["item_type", "Article"]]
2017-02-19T11:44:04.174846+00:00 app[web.1]:   User Load (62.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", nil]]
2017-02-19T11:44:04.180577+00:00 app[web.1]:   Rendered user_notifier/send_followers_email.html.erb within layouts/mailer (70.2ms)
2017-02-19T11:44:04.180686+00:00 app[web.1]: 
2017-02-19T11:44:04.180688+00:00 app[web.1]: UserNotifier#send_followers_email: processed outbound mail in 70.9ms
2017-02-19T11:44:04.266588+00:00 app[web.1]: Completed 500 Internal Server Error in 1049ms (Searchkick: 26.0ms | ActiveRecord: 545.3ms)
2017-02-19T11:44:04.267360+00:00 app[web.1]: [Rollbar] Reporting exception: Couldn't find User with 'id'=
2017-02-19T11:44:04.488171+00:00 heroku[router]: at=info method=POST path="/ahoy/events" host=ebwiki.org request_id=e108bde9-1e06-4774-9673-cb2056969ac1 fwd="72.76.197.157,162.158.62.162" dyno=web.1 connect=59ms service=576ms status=200 bytes=1092
2017-02-19T11:44:04.363330+00:00 app[web.1]: [Rollbar] Scheduling item
2017-02-19T11:44:04.363346+00:00 app[web.1]: [Rollbar] Sending item
2017-02-19T11:44:04.428502+00:00 heroku[router]: at=info method=POST path="/ahoy/events" host=ebwiki.org request_id=8d96afd6-79d2-42ec-9542-76bb06a3af92 fwd="72.76.197.157,162.158.62.162" dyno=web.1 connect=71ms service=560ms status=200 bytes=1092
2017-02-19T11:44:04.475876+00:00 heroku[router]: at=info method=POST path="/ahoy/events" host=ebwiki.org request_id=a46bea31-ee68-4923-8c64-763ae6566dcc fwd="72.76.197.157,162.158.62.162" dyno=web.1 connect=86ms service=525ms status=200 bytes=1092
2017-02-19T11:44:04.874526+00:00 heroku[router]: at=info method=POST path="/articles/alzona-fiero-smith" host=ebwiki.org request_id=8899c860-5bfa-42a7-b042-05445f0c7012 fwd="72.76.197.157,162.158.62.162" dyno=web.1 connect=65ms service=1908ms status=404 bytes=941
2017-02-19T11:44:04.868591+00:00 app[web.1]: [Rollbar] Success
2017-02-19T11:44:04.868697+00:00 app[web.1]: [Rollbar] Details: https://rollbar.com/instance/uuid?uuid=4725ef3c-258a-444d-b62c-f428b16f0db8 (only available if report was successful)
2017-02-19T11:44:04.868783+00:00 app[web.1]: [Rollbar] Exception uuid saved in env: 4725ef3c-258a-444d-b62c-f428b16f0db8
2017-02-19T11:44:04.871026+00:00 app[web.1]: 
2017-02-19T11:44:04.871028+00:00 app[web.1]: ActiveRecord::RecordNotFound (Couldn't find User with 'id'=):
2017-02-19T11:44:04.871030+00:00 app[web.1]:   app/views/user_notifier/send_followers_email.html.erb:2:in `_app_views_user_notifier_send_followers_email_html_erb__2996725571149815968_70131424182520'
2017-02-19T11:44:04.871030+00:00 app[web.1]:   app/mailers/user_notifier.rb:15:in `block in send_followers_email'
2017-02-19T11:44:04.871031+00:00 app[web.1]:   app/mailers/user_notifier.rb:13:in `each'
2017-02-19T11:44:04.871032+00:00 app[web.1]:   app/mailers/user_notifier.rb:13:in `send_followers_email'
2017-02-19T11:44:04.871032+00:00 app[web.1]:   app/controllers/articles_controller.rb:62:in `update'
2017-02-19T11:44:04.871033+00:00 app[web.1]: 
2017-02-19T11:44:04.871034+00:00 app[web.1]: 
2017-02-19T11:44:09.285915+00:00 heroku[web.1]: Process running mem=562M(109.6%)
2017-02-19T11:44:09.285915+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)```

**Comment by campgurus** [comment]
Checking back again, I also see that although the edit took effect, a new version was not created and no "commit" message was recorded for the history tab.

**Comment by rlgreen91** [comment]
Looking at the stack trace, I see that the issue is with sending the follower email, and that somehow we're running out of memory.  I took a look at how we call `send_followers_email` and I think we're just doing an inefficient query and/or operation there.  

I can't check right now, but it looks like when we call `send_followers_email`, we pass along `@article.followers`, which really is just an ActiveRecord relation for the set of users.  Then, when we call `users.each do...`, the relation is processed to create the actual array of user instances, which we then use to find the email address and send an email.  I can see how that can cause a memory problem once an article gets popular enough.

It seems like the key here is to have more efficient lookup of the email addresses.  It might be better to just pass the article to `send_followers_email` and within the method do a more specific query using `where` to get the array of emails, which we'll then iterate through to send the email.  Or we could make a separate database column in the articles table that consists of the list of followers email addresses.  Or we could have a separate table itself that consisted of some SQL join magic between articles and follower emails or that just contains a hash storing the article id as the key and a list of follower email addresses.  Actually that third suggestion is probably the best.  What do you think @trystant?

**Comment by rlgreen91** [comment]
Also, whatever route we take, we can also update `notify_of_removal` similarly (which, for style purposes, I'd like to see renamed as `send_deletion_notice`).

**Comment by campgurus** [comment]
Thanks for looking at this. I do now see the memory issue in the trace though. Seems odd that we would have a memory issue for 1 follower though.

**Comment by rlgreen91** [comment]
Oh, if there's only one follower for that particular article, then that means the memory leak is almost certainly somewhere else.  Yikes.

Quick question: does this bug appear again if you try to edit this same article now?  What if you try to edit a different article?  Like I said, if this has just one follower, that most likely means the memory leak is somewhere else, meaning that this exact bug should be hard to reproduce consistently.

Either way, I think we should go ahead and make this change, it's technical debt that we can go ahead and resolve rather than an actual premature optimization.  Do you want to tackle this or should I just mark this as a quick fix for the next available person?

**Comment by campgurus** [comment]
In terms of behavior in the app.  Sometimes it works, creates a paper_trail version that I can see in the history page. But it stops pretty quickly.

I am not sure how to fix it. I did notice this morning, looking at the heroku dashboard that we have a lot of memory errors.  So I think that may be the same thing. I am not sure how to fix the leak, but I am wondering if spinning up another heroku dyno (server) may be the answer until we can figure that out.

**Comment by campgurus** [comment]
This issue seems related to #821

**Comment by trystant** [comment]
This has been fixed.
